#spring.application.name=mpl
#
#jwt.secret=mysecretmysecretmysecretmysecret
#
## Database Configuration (creates/updates 'mpl' database)
#spring.datasource.url=jdbc:mysql://localhost:3306/mpl?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=Hari@12345
#spring.jpa.hibernate.ddl-auto=update
#
## Set port to 8080 to match React's fetch calls
#server.port=8080



spring.application.name=mpl

jwt.secret = mysecretmysecretmysecretmysecret
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/mpl}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}